update workflow

diff --git a/.github/workflows/build-deploy.yml b/.github/workflows/build-deploy.yml
--- a/.github/workflows/build-deploy.yml
+++ b/.github/workflows/build-deploy.yml
@@ -84,13 +84,13 @@ jobs:
           key: ${{ secrets.SSH_PRIVATE_KEY }}
           port: ${{ secrets.SSH_PORT }}
           script: |
-          pm2 show ${{secrets.PM2_PROCESS_NAME}} || echo "Process not found"
-          if [ $? -ne 0 ]; then
-            echo "Process not found, starting it..."
-            pm2 --name ${{secrets.PM2_PROCESS_NAME}} start ${{ secrets.HOME }}/txt-share.barcelos.dev/api/api.js
-          else
-            pm2 -s restart ${{secrets.PM2_PROCESS_NAME}}
-          fi
+            pm2 show ${{secrets.PM2_PROCESS_NAME}} || echo "Process not found"
+            if [ $? -ne 0 ]; then
+              echo "Process not found, starting it..."
+              pm2 --name ${{secrets.PM2_PROCESS_NAME}} start ${{ secrets.HOME }}/txt-share.barcelos.dev/api/api.js
+            else
+              pm2 -s restart ${{secrets.PM2_PROCESS_NAME}}
+            fi
 
       - name: Restart Nginx
         uses: appleboy/ssh-action@master
